version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookswap-db
    environment:
      POSTGRES_DB: aplicacao_pds       
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: 2003          
    ports:
      - "5433:5432"                    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: bookswap-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookswap.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: